### ISSUE TITLE
EDA files, and question

### ISSUE THREAD

**Issue by BRFud** [ClusterM/famicom-dumper#3]
Hi,

I very new to nes development / cart dumping and I had a few questions about this project:

1. Are the EDA files available for this project(Kicad or Eagle, etc)? As I am thinking I may want to edit the components slightly and re-arrange the PCB.
2. What are the main differences/advantages/limitations between this project and Kazzo or other NES/famicom cart programmers/dumpers?

Thanks for your time and your work on this and other projects.

**Comment by mindstation** [comment]
There are the EDA files in the project.
It's a "board/famicom_dumper.lay6" for the first version board. The file was created under Sprint Layout.
The "board2/famicom_dumper.dip" and schematic "schematics/famicom_dumper.dch" was created under DipTrace (it's free for small circuit boards).

I did not use any other NES/Famicom dumpers and can't answer the other question. Maybe the author can.
